### ISSUE TITLE
Multiple favorites of the same product

### ISSUE THREAD

**Issue by tuto1902** [alanmontgomery/ionic-ecommerce-example#1]
If you click the favorite button on an already favorited product, it keeps adding it to the favorites store. Also, attempting this inside the FavouriteProducts.js page causes the list multiply.

May I suggest adding the following logic for the addToFavourites method (might even consider calling it toggleFavourite)

````Javascript
export const addToFavourites = (categorySlug, productID) => {
    FavouritesStore.update(s => {
        if (s.product_ids.find(id => id === `${ categorySlug }/${ parseInt(productID) }`)) {
            s.product_ids = s.product_ids.filter(id => id !== `${ categorySlug }/${ parseInt(productID) }`);
        } else {
            s.product_ids = [ ...s.product_ids, `${ categorySlug }/${ parseInt(productID) }` ];
        }
    });
}
````

I would also suggest adding this in FavouriteProducts.js

````Javascript
    useEffect(() => {

        const getFavourites = () => {
            // Clear search results on each call
            setSearchResults([]);

            favourites.forEach(favourite => {
                ....
            });
        }
        getFavourites();
    }, [ favourites ]);
````

Finally, add a check in ProductCard.js to prevent errors when productCartRef.current is null

````Javascript
        setTimeout(() => {
            if (productCartRef.current) {
                productFavouriteRef.current.classList.remove("animate__fadeOutTopRight");
                productFavouriteRef.current.style.display = "none";
            }
        }, 500);
````

If you would grant me push permissions I can submit a pull request.

Cheers

**Comment by alanmontgomery** [comment]
Thanks! Yes - as a rough example, I left some things "unfinished" 😊 I've invited you as a collaborator, feel free to push a change in when you're ready
